### Import Library

In [1]:
import pandas as pd
import numpy as np
import matplotlib as mat
from scipy import stats

### Read data csv

In [2]:
df = pd.read_csv("data/covid_19_indonesia_time_series_all.csv")
df

,Date,Location ISO Code,Location,New Cases,New Deaths,New Recovered,New Active Cases,Total Cases,Total Deaths,Total Recovered,...,Latitude,New Cases per Million,Total Cases per Million,New Deaths per Million,Total Deaths per Million,Total Deaths per 100rb,Case Fatality Rate,Case Recovered Rate,Growth Factor of New Cases,Growth Factor of New Deaths
0,3/1/2020,ID-JK,DKI Jakarta,2,0,0,2,39,20,75,...,-6.204699,0.18,3.60,0.0,1.84,0.18,51.28%,192.31%,NaN,NaN
1,3/2/2020,ID-JK,DKI Jakarta,2,0,0,2,41,20,75,...,-6.204699,0.18,3.78,0.0,1.84,0.18,48.78%,182.93%,1.00,1.00
2,3/2/2020,IDN,Indonesia,2,0,0,2,2,0,0,...,-0.789275,0.01,0.01,0.0,0.00,0.00,0.00%,0.00%,NaN,NaN
3,3/2/2020,ID-RI,Riau,1,0,0,1,1,0,1,...,0.511648,0.16,0.16,0.0,0.00,0.00,0.00%,100.00%,NaN,NaN
4,3/3/2020,ID-JK,DKI Jakarta,2,0,0,2,43,20,75,...,-6.204699,0.18,3.96,0.0,1.84,0.18,46.51%,174.42%,1.00,1.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31817,9/15/2022,ID-SA,Sulawesi Utara,37,0,0,37,52770,1213,50997,...,1.259638,14.01,19974.38,0.0,459.14,45.91,2.30%,96.64%,2.85,1.00
31818,9/15/2022,ID-SB,Sumatera Barat,13,0,3,10,104640,2371,102066,...,-0.850253,2.36,18959.11,0.0,429.59,42.96,2.27%,97.54%,6.50,1.00
31819,9/15/2022,ID-SS,Sumatera Selatan,16,0,1,15,82198,3376,78510,...,-3.216212,1.95,10002.74,0.0,410.83,41.08,4.11%,95.51%,3.20,1.00
31820,9/15/2022,ID-SU,Sumatera Utara,50,0,5,45,158866,3288,154924,...,2.191894,3.36,10680.15,0.0,221.04,22.10,2.07%,97.52%,1.92,1.00
31821,9/16/2022,IDN,Indonesia,2358,27,2997,-666,6405044,157876,6218708,...,-0.789275,8.89,24153.07,0.1,595.34,59.53,2.46%,97.09%,0.89,1.29

In [4]:
# New case per hari di Jakarta
case_Jakarta = df[df["Location"] == "DKI Jakarta"][["Date", "New Cases"]].groupby("Date").sum()
# New case per hari di Jawa Barat
case_JB = df[df["Location"] == "Jawa Barat"][["Date", "New Cases"]].groupby("Date").sum()

print(f'Rata - rata new case Jakarta : {round(case_Jakarta["New Cases"].mean(),2)}')
print(f'Rata - rata new case Jawa Barat : {round(case_JB["New Cases"].mean(),2)}')

Rata - rata new case Jakarta : 1520.42
Rata - rata new case Jawa Barat : 1266.16

Rata - rata new case Jakarta : 1520.42

Rata - rata new case Jawa Barat : 1266.16

H0: μ_Jakarta = μ_JawaBarat

H1: μ_Jakarta != μ_JawaBarat

Apakah rata-rata new case Jakarta tidak ada perbedaan signifikan pada rata-rata new case Jawa Barat atau terdapat perbedaan yang signifikan

### Pembuktian dengan single sample two sided

In [5]:
t_stat, p_val = stats.ttest_ind(case_Jakarta,case_JB)
print('P-value:',p_val[0])
print('t-statistics:',t_stat[0])

P-value: 0.020253989345214322
t-statistics: 2.3236112018015596

Hasil P-value adalah 0.02 yaitu dibawah critical value (0.05), maka hipotesis null yang menyatakan tidak ada perbedaan signifikan dapat ditolak. Sehingga rata-rata new case Jakarta dan Jawa Barat berbeda cukup signifikan.